[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = [
  "pip install --break-system-packages -r requirements.txt",
  "playwright install chromium --with-deps"
]

[start]
cmd = "python main.py"
